### PR TITLE
data_recorder

### PR DESCRIPTION
**Pull request by voshch**
Depends/supersedes #111

Working data recorder using `record_data:=true`.

### CODE REVIEW

**Comment by voshch** [comment]
undraft & merge when #111 is merged

**Comment by voshch** [comment]
@linhdoan8

**Review by linhdoan8 — APPROVED** [review]

**Comment by linhdoan8** [comment]
why are there so many new files included in this PR when its only about the data recorder? @voshch 
@tuananhroman check pls

**Comment by voshch** [comment]
> why are there so many new files included in this PR when its only about the data recorder? @voshch @tuananhroman check pls

changed the base branch, only contains data recorder now

**Review by linhdoan8 — APPROVED** [review]

**Pull request merged**
