### PR TITLE
New Task Mode "Zones"

### PR DESCRIPTION
**Pull request by ddiaz-0**
Adds a new task mode for obstacles which assigns dynamic obstacles (humans) specific types and calculates the waypoints for them semantically based on the type, meaning that waypoints and spawn points for each type are restricted to specific zones (polygons) which are coherent to the type (e.g. in a hospital setting: janitor should not visiting patient rooms, visitors only move in public spaces, nurses move from patient room to patient room).
Zones will be defined for each map which are located in the simulation-setup repository, therefore see also the corresponding PR there (# 22). 🖥️

### CODE REVIEW

**Comment by voshch** [comment]
@ddiaz-0 please test & review (with a short comment) for functionality, then undraft when ready.
Also goes for https://github.com/Arena-Rosnav/arena-simulation-setup/pull/22.

**Comment by voshch** [comment]
@nhat-luu Test everything, mark ready for review, amend docs

**Review by voshch — DISMISSED** [review]
good

**Review by voshch — APPROVED** [review]
good

**Comment by ddiaz-0** [comment]
Okay, then last step is merging @voshch @linhdoan8

**Comment by voshch** [comment]
will do once unity is merged, don't wanna give someone a nervous breakdown

**Pull request merged**
