### PR TITLE
full rework of task_generator

### PR DESCRIPTION
**Pull request by voshch**

### CODE REVIEW

**Comment by voshch** [comment]
@linhdoan8 
Test with:

`roslaunch arena_bringup start_arena.launch simulator:=flatland task_mode:=scenario map_file:=empty_map`

configure task_modes in `arena-rosnav/arena_bringup/configs/task_generator.yaml` (documented in docs)

switch
- simulator to flatland|gazebo
- task_mode to scenario|parametrized|random|staged|dynamic_map_random|dynamic_map_staged
- dynamic_map require map_file:=dynamic_map

**Comment by linhdoan8** [comment]
Issues:
- Rviz crashed, gazebo continues to run without problems: why?
- after rviz crashes, when opening new rviz, robot model cannot be loaded in, laserscan not publishing anything
- static obstacles still spawning inside walls sometimes
- actors invisible to the robot? no physics when robot touches the humans, laserscan gets shaken which means colision has some effect, but actors are not affected
- actors not seeing the robot, not actively avoiding even though robot force set very high 
- MPC, DWA planners extremely laggy, slow, check topics, planners not correct
- dynamic tasks not working
- flatland gives error:  raise ValueError(
ValueError: 'DYNAMIC_MAP_RANDOM' task can only be used with dynamic map, otherwise the MapGenerator isn't used. (expected: dynamic_map, got: map_empty)
[jackal/move_base-2] killing on exit
[jackal/transform_broadcaster-1] killing on exit

**Comment by voshch** [comment]
>     Rviz crashed, gazebo continues to run without problems: why?
>     after rviz crashes, when opening new rviz, robot model cannot be loaded in, laserscan not publishing anything
Instructions to reproduce this?
Behavior after no_of_episodes is reached ("regular" shutdown) is consistent with the target branch.

>     static obstacles still spawning inside walls sometimes
Regression testing shows that spawning behavior is identical to target branch for both small (n=5) and large (n=50) amounts of static obstacles.

>     actors invisible to the robot? no physics when robot touches the humans, laserscan gets shaken which means colision has some effect, but actors are not affected
This is a simulator limitation. Considering this a non-problem since pedestrian collisions result in a catastrophic failure and should abort the simulation.

>     actors not seeing the robot, not actively avoiding even though robot force set very high
Regression testing shows that the pedsim cube actors behave the same way. Adding pedestrian robot sensing requires additional pedsim extensions outside of the scope of this PR.

>     MPC, DWA planners extremely laggy, slow, check topics, planners not correct
Regression testing reveals that this behavior comes from the target branch. Outside of the scope of this PR, should be documented in a separate issue though. (tested `local_planner:=dwa` with `model:=jackal`, planner seems to get reset multiple times per second)

>     dynamic tasks not working
>    ValueError: 'DYNAMIC_MAP_RANDOM' task can only be used with dynamic map, otherwise the MapGenerator isn't used. (expected: dynamic_map, got: map_empty)
_Using dynamic_map requires `map_file:=dynamic_map` to be set_, this applies to all simulators and both `dynamic_map_*` task_modes. The very first dry run (after pulling arena-simulation-setup) may fail, but subsequent restarts work every time.

**Comment by voshch** [comment]
already merged through https://github.com/Arena-Rosnav/arena-rosnav/pull/68 and https://github.com/Arena-Rosnav/arena-rosnav/commit/6cfa4c3f42dc00b6c72ff8e9fba9a1ae9cba471d

**Pull request closed without merging**
