### PR TITLE
robot launch file support + pedsim visualization

### PR DESCRIPTION
**Pull request by voshch**
+ default config adjustments

### CODE REVIEW

**Comment by voshch** [comment]
@tuananhroman These changed shouldn't affect your WIP, but please confirm so we can be sure

**Review by linhdoan8 — COMMENTED** [review]
check with training pipeline first

**Comment by voshch** [comment]
can be merged imo

**Review by tuananhroman — APPROVED** [review]
does not interfere with training pipeline, can be merged!

**Review by linhdoan8 — APPROVED** [review]
All ok

**Pull request merged**
