### PR TITLE
Pedsim Integration Training

### PR DESCRIPTION
**Pull request by tuananhroman**
Pedsim usable for all training modes.

### CODE REVIEW

**Review by linhdoan8 — DISMISSED** [review]
all ok, except conflicts in one file, please resolve

**Review by linhdoan8 — CHANGES_REQUESTED** [review]
resolve merge conflicts in reward_function.py @tuananhroman

**Comment by tuananhroman** [comment]
Done @linhdoan8

**Comment by tuananhroman** [comment]
@linhdoan8 Issues resolved.

**Pull request merged**
