### PR TITLE
Semantic Training

### PR DESCRIPTION
**Pull request by tuananhroman**
Training pipeline should be running smoothly again with some new features.

Features:
- More modular action- and observation space management
- Retrieval and potential encoding of semantic information
- New Reward function module
- Fully documented code

These tasks remain:
- Evaluate how many step world calls are necessary to fully update the simulation and how to reduce these steps.
- Request global plan from the newly integrated mbf.
- Test the throughput and speed of different components.

### CODE REVIEW

**Comment by tuananhroman** [comment]
Depends on [Rosnav-rl PR #15](https://github.com/Arena-Rosnav/rosnav-rl/pull/15)

**Review by voshch — DISMISSED** [review]
exquisite

**Comment by tuananhroman** [comment]
@voshch Review needed

**Review by voshch — APPROVED** [review]
yeah

**Pull request merged**
