### PR TITLE
Training Pipeline: New TaskGenerator Structure and SB3 Update

### PR DESCRIPTION
**Pull request by tuananhroman**

### CODE REVIEW

**Comment by tuananhroman** [comment]
@voshch

**Review by voshch — APPROVED** [review]
Evaluation works well, except for:
- random (and any derivatives) don't reset the task when the goal is reached (either is_goal_reached is broken or the reset is not propagated properly) -> this is probably my mistake and I will fix it in subsequent PRs

Requesting re-review from @tuananhroman to make sure I didn't break training with my changes here (but I physically can't add the author as a reviewer)

**Comment by linhdoan8** [comment]
@tuananhroman

**Review by linhdoan8 — APPROVED** [review]
all ok

**Pull request merged**
